server:
  port: 7050
  
spring:
  application:
    name: CUSTOMER-SERVICE
    
  datasource:
    url: jdbc:mysql://localhost:3306/customer?createDatabaseIfNotExist=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
      
  cloud:
    config:
      enabled: true
      
  config:
    import: configserver:http://localhost:9292
    
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            type:
              mapping: event:com.varsha.customer.entity.Customer
     



management:
  endpoints:
    web:
      exposure:
        include: '*'
  tracing:
    sampling:
      probability: 1.0
      
logging:
  file:
    name: logFile.log
    
    