server:
  port: 9192

#Security
secretkey: "5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437"
#token duration in minutes
tokenduration: 30


logging:
  level:
    org.springframework.security: TRACE

  
spring:
  application:
    name: AUTH-SERVICE
    
  config:
    import: configserver:http://localhost:9292
  cloud:
    config:
      enabled: true
      

management:
  endpoints:
    web:
      exposure:
        include: '*'
  tracing:
    sampling:
      probability: 1.0
      

    
